org.gradle.jvmargs=-Xms1g -Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xms1g -Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
kotlin.code.style=official
android.useAndroidX=true

GROUP=io.github.phompang.fermata
VERSION_NAME=0.1.0-SNAPSHOT

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/PhompAng/fermata
POM_SCM_URL=https://github.com/PhompAng/fermata
POM_SCM_CONNECTION=scm:git:git://github.com/PhompAng/fermata.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/PhompAng/fermata.git
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=PhompAng
POM_DEVELOPER_NAME=PhompAng
POM_DEVELOPER_URL=https://github.com/PhompAng
